Project3
Macbeth-Klm/Tinkoff-java-course-2023 pull request #10
Opened 2023-11-19 16:04 UTC by Macbeth-Klm

2023-11-19 16:14 UTC, Macbeth-Klm commented
Здравствуйте!

Прошу прощения за то, что в PR попал `Main` из второго проекта. 

Дело в том, что он не был `final` и checkstyle просил меня сделать его `final`, так как у него конструктор приватный. На чеки на GitHub это никак не повлияло, поэтому я, соответственно, не обратил на это внимание, когда выполнял проект2.

Прошу прощения ещё раз и спасибо.

2023-11-22 12:45 UTC, nexen505 requested changes

2023-11-22 12:45 UTC, nexen505 commented on src/main/java/edu/project3/LogAnalyser.java
> +                return (from == null || !timeLocal.isBefore(from))
Мысль: можно сделать всю проверку даты методом `LogRecord`.

2023-11-22 12:45 UTC, nexen505 commented on src/main/java/edu/project3/LogAnalyser.java
> +        List<Long> values = new ArrayList<>();
Проблема: тут и в соседних методах используется сложная манипуляция несколькими коллекциями для сортировки.

Предложение: воспользоваться Stream API с преобразованием `unsortedMap.entrySet()`.

2023-11-22 12:45 UTC, nexen505 commented on src/main/java/edu/project3/parsers/CommandParser.java
> +        try (var response = newHttpClient()) {
Опечатка:

```java suggestion
        try (var client = newHttpClient()) {
```

2023-11-24 13:28 UTC, nexen505 approved these changes

2023-11-24 14:32 UTC, merged