hw7: hw7 has been done
Macbeth-Klm/Tinkoff-java-course-2023 pull request #11
Opened 2023-11-24 22:45 UTC by Macbeth-Klm

2023-11-27 13:01 UTC, nexen505 requested changes

2023-11-27 13:01 UTC, nexen505 commented on src/main/java/edu/hw7/task3and3point5/SynchronizedDatabase.java
> +        return nameTable.entrySet().stream()
Проблема: тут и далее получение по индексу требует прохода по всем ключам, что неоптимально.

Предложение: воспользоваться тут и далее методом `Map#get`.

2023-11-27 13:01 UTC, nexen505 commented on src/main/java/edu/hw7/task3and3point5/ReadWriteLockDatabase.java
> +        readWriteLock.writeLock().unlock();
Проблема: так лок может остаться в зависшем состоянии при непредвиденных ошибках.

Предложение: воспользоваться следующим паттерном при работе с локами.

```java
lock.lock();
try {
    // perform some critical operation
} finally {
    lock.unlock();
}

2023-11-27 13:01 UTC, nexen505 commented on src/main/java/edu/hw7/task4/PiCalculator.java
> +        PiCalculatorThread[] threads = new PiCalculatorThread[threadCount];
Проблема: такой подход приводит к необходимости ручного управления потоками.

Предложение: изменить реализацию на использование `Executors#newFixedThreadPool`.

2023-11-27 19:56 UTC, Macbeth-Klm commented
![image](https://github.com/Macbeth-Klm/Tinkoff-java-course-2023/assets/105516683/5a812892-f732-469b-a8e8-e87e3118f60c)

2023-11-28 13:51 UTC, nexen505 requested changes

2023-11-28 13:51 UTC, nexen505 commented on src/main/java/edu/hw7/task4/PiCalculator.java
> +        long threadTotalPoint = totalPoints / threadCount;
Проблема: кажется, так часть точек выпадет из рассмотрения, если деление не целое.

Предложение: учесть наличие остатка точек при расчете.

2023-11-28 13:51 UTC, nexen505 commented on src/main/java/edu/hw7/task4/PiCalculator.java
> +            Math.pow(point.x() - CIRCLE_CENTER.x(), 2) + Math.pow(point.y() - CIRCLE_CENTER.y(), 2)
Мысль: можно сократить число математических операций, если считать, что мы выбираем точки с `0 <= x < 1` и `0 <= y < 1` в четверти круга единичного радиуса с центром в точке (0,0).

2023-11-28 18:00 UTC, Macbeth-Klm commented
![image](https://github.com/Macbeth-Klm/Tinkoff-java-course-2023/assets/105516683/c713f68c-440c-4f28-b7d2-a599005e6e13)

2023-11-29 07:27 UTC, nexen505 approved these changes

2023-11-29 14:34 UTC, merged