hw8: hw8 has been done
Macbeth-Klm/Tinkoff-java-course-2023 pull request #12
Opened 2023-12-02 20:14 UTC by Macbeth-Klm

2023-12-02 20:18 UTC, Macbeth-Klm commented
![image](https://github.com/Macbeth-Klm/Tinkoff-java-course-2023/assets/105516683/1b4295ab-4b0d-48fc-bc5a-b2f439f503cd)

2023-12-04 13:29 UTC, nexen505 requested changes

2023-12-04 13:29 UTC, nexen505 commented on src/main/java/edu/hw8/task1/Server.java
> +            threadPool.shutdown();
Проблема: пул закрывается дважды.

Предложение: убрать это закрытие и ожидание завершения в пользу имеющегося `try-with-resources`.

2023-12-04 13:29 UTC, nexen505 commented on src/main/java/edu/hw8/task1/Server.java
> +            while (isRunning) {
Мысль: можно упростить реализацию открытия-закрытия, если завязаться на `serverSocket.isClosed()`. Тогда закрытие сервера можно реализовать через закрытие сокета без флагов и доп.команды клиента.

2023-12-04 13:29 UTC, nexen505 commented on src/main/java/edu/hw8/task2/FixedThreadPool.java
> +                    Runnable task = taskQueue.poll();
Проблема: так поток будет busy-looping.

Предложение: использовать, например, `java.util.concurrent.BlockingQueue#take`

2023-12-04 13:29 UTC, nexen505 commented on src/main/java/edu/hw8/task2/FixedThreadPool.java
> +                thread.join();
Проблема: возможна блокировка потока.

Предложение: использовать `java.lang.Thread#join(java.time.Duration)` и прервать поток вручную в случае неудачи в ожидании.

2023-12-04 13:29 UTC, nexen505 commented on src/main/java/edu/hw8/task3/PasswordGenerator.java
> +public class PasswordGenerator {
Косметика: можно реализовать интерфейс `java.util.Iterator<String>` для идиоматичности.

2023-12-05 01:43 UTC, Macbeth-Klm commented
![image](https://github.com/Macbeth-Klm/Tinkoff-java-course-2023/assets/105516683/2a0b992d-77e7-4485-b1e0-9f6685a13911)

2023-12-05 13:53 UTC, nexen505 approved these changes

2023-12-05 14:16 UTC, merged