hw9: hw9 has been done
Macbeth-Klm/Tinkoff-java-course-2023 pull request #13
Opened 2023-12-05 00:09 UTC by Macbeth-Klm

2023-12-08 11:06 UTC, nexen505 requested changes

2023-12-08 11:06 UTC, nexen505 commented on src/main/java/edu/hw9/task1/StatsCollector.java
> +        return statistics;
Проблема: возвращается мутируемый список.

Предложение: обернуть в `Collections#unmodifiableList`.

2023-12-08 11:06 UTC, nexen505 commented on src/main/java/edu/hw9/task1/StatsCollector.java
> +        threadPool.shutdown();
Мысль: вместо этих вызовов можно воспользоваться `threadPool.close()`.

2023-12-08 11:06 UTC, nexen505 commented on src/main/java/edu/hw9/task1/StatsCollector.java
> +            double value = switch (metricName) {
Косметика: по заданию подразумевается, что в качестве имени передается имя набора всех показателей, а не одного конкретного.

2023-12-08 11:06 UTC, nexen505 commented on src/main/java/edu/hw9/task2/DirectoriesTask.java
> +        List<Path> filesAndDirectories;
Актуально и для других решений задания.

Мысль: думаю, можно обойтись без промежуточной коллекции, создавая задачи сразу из потока файлов.

2023-12-08 11:06 UTC, nexen505 commented on src/main/java/edu/hw9/task2/FilesExtensionTask.java
> +            result.addAll(task.join());
Актуально и для других решений задания.

Проблема: задачи создаются по одной и ожидаются по одной.

Предложение: сначала форкнуть все задачи и дождаться их все после запуска.

2023-12-08 11:06 UTC, nexen505 commented on src/main/java/edu/hw9/task3/MultiThreadWaveLeeAlgorithm.java
> +                    task.join();
Проблема: в таком виде выходит, что алгоритм не параллельный, так как каждая запущенная задача ждет очередную запущенную и в итоге все под капотом выполнится последовательно.

Предложение: есть ощущение, что параллелизация алгоритма Ли для данного курса - задача долгая. Возьми алгоритм попроще.

2023-12-09 08:48 UTC, Macbeth-Klm commented on src/main/java/edu/hw9/task3/MultiThreadWaveLeeAlgorithm.java
> +                    task.join();
Здравствуйте! 
Я попытался изначально исправить алгоритм Ли, но всё свелось к тому, что я два раза обходил лабиринт и изменил исходник в проекте №2. 
Поэтому я, как вы и предложили, взял более простой алгоритм и класс Maze.java вернул в исходное состояние.
Спасибо!

2023-12-12 12:08 UTC, nexen505 approved these changes

2023-12-12 15:23 UTC, merged