project4: project4 has been done
Macbeth-Klm/Tinkoff-java-course-2023 pull request #14
Opened 2023-12-07 23:17 UTC by Macbeth-Klm

2023-12-07 23:29 UTC, Macbeth-Klm commented
Ссылки на сообщения с изображениями и скриншот сравнения скорости работы однопоточной и многопоточной версии представлены ниже.
https://t.me/c/1690654462/10849
https://t.me/c/1690654462/10864

![image](https://github.com/Macbeth-Klm/Tinkoff-java-course-2023/assets/105516683/51f7dd35-1755-450f-b680-6fe309346f50)

2023-12-14 08:55 UTC, nexen505 requested changes

2023-12-14 08:55 UTC, nexen505 commented on src/main/java/edu/project4/FractalInferno.java
> +            AffineTransformation[] affines = createAffineTransformation(affineCount);
Косметика: это можно из `try-catch` вытащить.

2023-12-14 08:55 UTC, nexen505 commented on src/main/java/edu/project4/NonLinearTransformator.java
> +    public static Point getPoint(double x, double y, NonLinearType type) {
Предложение: сделать это методом класса `Point`.

2023-12-14 08:55 UTC, nexen505 commented on src/main/java/edu/project4/FractalInferno.java
> +            x = affine.a() * x + affine.b() * y + affine.c();
Предложение: сделать аффинное преобразование координат точки методом класса точки.

2023-12-14 08:55 UTC, nexen505 commented on src/main/java/edu/project4/FractalInferno.java
> +    private Point rotate(Point point, double theta) {
Предложение: сделать это методом класса `Point`

2023-12-14 08:55 UTC, nexen505 commented on src/test/java/edu/project4/FractalInfernoTest.java
> +public class FractalInfernoTest {
Предложение: после предложенного рефакторинга расширить набор юнит-тестов.

2023-12-19 12:06 UTC, nexen505 approved these changes

2023-12-19 13:40 UTC, merged