project1: project1 has been done
Macbeth-Klm/Tinkoff-java-course-2023 pull request #4
Opened 2023-10-16 23:02 UTC by Macbeth-Klm

2023-10-23 14:05 UTC, nexen505 requested changes

2023-10-23 14:05 UTC, nexen505 commented on src/main/java/edu/project1/ConsoleHangman.java
> +public final class ConsoleHangman {
Проблема: нет `main`-метода, который можно запустить, чтобы проверить работоспособность игры.

Предложение: добавить его.

2023-10-23 14:05 UTC, nexen505 commented on src/main/java/edu/project1/Player.java
> +    private static final Scanner SCANNER = new Scanner(System.in);
Проблема: такой подход затрудняет тестирование.

Предложение: сделать `Scanner` параметром конструктора и полем `Session`, что позволит при тестировании его мокать.

2023-10-23 14:05 UTC, nexen505 commented on src/main/java/edu/project1/Session.java
> +        if (playerAnswer.length() == 1) {
Проблема: ситуация некорректного ввода не обрабатывается и засчитывается как неудачная попытка.

Предложение: улучшить UX выводом просьбы ввести один символ.

2023-10-23 14:05 UTC, nexen505 commented on src/main/java/edu/project1/Session.java
> +        if (realWord.length() > this.maxAttempts) {
Мысль: кажется, данная проверка некорректно работает в случае, если в слове повторяются буквы.

2023-10-23 14:05 UTC, nexen505 commented on src/main/java/edu/project1/Session.java
> +                sb.deleteCharAt(i);
Предложение: воспользоваться методом `replace`.

2023-10-27 11:11 UTC, nexen505 requested changes

2023-10-27 11:11 UTC, nexen505 commented on src/main/java/edu/project1/ConsoleHangman.java
> +                break;
Косметика: в такой ситуации яснее делать "быстрый выход" через вызов `return`.

2023-10-27 11:11 UTC, nexen505 commented on src/main/java/edu/project1/ConsoleHangman.java
> +                break;
Косметика: в такой ситуации яснее делать "быстрый выход" через вызов `return`.

2023-10-27 11:11 UTC, nexen505 commented on src/main/java/edu/project1/ConsoleHangman.java
> +                GameMessage.lose();
Косметика: это можно вынести за цикл, так как по выходе из него ясно, что число попыток превышено.

2023-10-27 11:11 UTC, nexen505 commented on src/main/java/edu/project1/ConsoleHangman.java
> +    private static final String COMMAND_GIVE_UP = "/gg";
Проблема: пользователь не знает о таком сценарии.

Предложение: подсказать пользователю, как можно сдаться.

2023-10-27 11:11 UTC, nexen505 commented on src/main/java/edu/project1/Session.java
> +                attempts++;
Проблема: повторный ввод ранее неугаданной буквы приводит к трате попытки и поражению.

Предложение: предусмотреть, чтобы траты попытки не происходило, и вывести пользователю просьбу указать другую букву.

2023-10-27 11:11 UTC, nexen505 commented on src/main/java/edu/project1/ConsoleHangman.java
> +                GameMessage.lose();
Проблема: при проигрыше или сдаче пользователь не узнает, что за слово было.

Предложение: вывести в конце проигранной игры пользователю загаданное слово.

2023-10-27 11:11 UTC, nexen505 commented on src/main/java/edu/project1/Session.java
> +        List<Character> uniqueCharList = new ArrayList<>();
Предложение: посчитать это с помощью `Set`. Это избавит от необходимости делать `contains` + `add`, что упростит алгоритмическую сложность вычисления.

2023-10-27 11:11 UTC, nexen505 commented on src/main/java/edu/project1/Session.java
> +        char playerAnswerChar = playerAnswer.toCharArray()[0];
Мысль: в метод можно сразу передать единственный символ.

2023-10-27 11:11 UTC, nexen505 commented on src/main/java/edu/project1/Session.java
> +                sb.replace(i, i + 1, playerAnswer);
Косметика:

```java suggestion
                sb.setCharAt(i, playerAnswerChar);
```

2023-10-27 11:12 UTC, nexen505 commented on src/main/java/edu/project1/ConsoleHangman.java
> +            session.makeMove();
Проблема: при первом вводе пользователь не знает, какого размера слово надо угадывать.

Предложение: добавить вывод зашифрованного слова при входе в игру.

2023-10-28 14:50 UTC, Macbeth-Klm commented on src/main/java/edu/project1/ConsoleHangman.java
> +            session.makeMove();
Подскажите, пожалуйста, как лучше поступить: 
Так:
![image](https://github.com/Macbeth-Klm/Tinkoff-java-course-2023/assets/105516683/0990e10e-c586-48d8-a691-81df92206569)
![image](https://github.com/Macbeth-Klm/Tinkoff-java-course-2023/assets/105516683/ebcfd64a-8ced-4b65-a9a5-2bc0b73a1843)
Или так:
![image](https://github.com/Macbeth-Klm/Tinkoff-java-course-2023/assets/105516683/84801f6d-dfbd-4665-bfc6-ddc70a381dca)
![image](https://github.com/Macbeth-Klm/Tinkoff-java-course-2023/assets/105516683/0d537864-154a-4ed7-8d8f-be85f300b98e)
Дело в том, что у меня уже имеется отдельный метод GameMessage.wordStatus() для вывода зашифрованного слова, который используется в методе Session.makeMove(). 
![image](https://github.com/Macbeth-Klm/Tinkoff-java-course-2023/assets/105516683/942cfbef-e252-4c8e-9353-4efb60daf70b)
С точки зрения косметики как лучше поступить: изменить первый метод или просто вызвать к ряду два метода класса GameMessage в методе ConsoleHangman.run()?

2023-10-28 15:32 UTC, Macbeth-Klm commented on src/main/java/edu/project1/Session.java
> +        List<Character> uniqueCharList = new ArrayList<>();
Так?
![image](https://github.com/Macbeth-Klm/Tinkoff-java-course-2023/assets/105516683/1c283c77-7df5-40e7-9dd2-e3ee2536831e)

2023-10-31 08:07 UTC, nexen505 commented on src/main/java/edu/project1/ConsoleHangman.java
> +            session.makeMove();
Мне кажется, отдельный метод переиспользовать лучше.

2023-11-01 05:56 UTC, nexen505 requested changes

2023-11-01 05:56 UTC, nexen505 commented on src/main/java/edu/project1/Session.java
> +                answerHistory.add(playerAnswer);
Мысль: `contains` + `add` можно заменить проверкой возвращаемого значения `add`, если заменить `List` на `Set`

2023-11-01 05:56 UTC, nexen505 commented on src/main/java/edu/project1/Session.java
> +    public void makeMove(List<String> answerHistory) {
Проблемы:
- нет смысла делать это параметром метода, так как это внутренняя дополнительная структура.
- список приводит к возможности добавления дубликатов по ошибке и дает линейную сложность на операции `contains`

Предложение: перейти в реализации к полю типа `Set<String>`

2023-11-01 05:56 UTC, nexen505 commented on src/main/java/edu/project1/Session.java
> +        if (playerAnswer.length() == 1) {
Мысль: как я подсвечивал ранее, удобнее будет внутри `if` достать `playerAnswer.charAt(0)` и использовать только этот символ без строки целиком.

2023-11-03 13:34 UTC, nexen505 approved these changes

2023-11-03 14:14 UTC, merged